jobs:
  build:
    permissions:
      contents: "write"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      with:
        fetch-depth: 0
        submodules: "recursive"
        token: "${{secrets.GIT_PUSH_TOKEN}}"
    - name: "Create release commit"
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y git-buildpackage
        export DEBEMAIL="dev@radxa.com"
        export DEBFULLNAME='"Radxa Computer Co., Ltd"'
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        make dch
      shell: "bash"
    - name: "Test"
      run: |
        sudo apt-get build-dep --no-install-recommends -y .
        make all test deb
      shell: "bash"
    - name: "Test"
      run: |
        git push
      shell: "bash"
name: "Create release"
"on":
  workflow_dispatch: {}
permissions: {}